const TASKS_NAMES = {
  ScheduleDailyMembersDataSync: 'ScheduleDailyMembersDataSync',
  ScheduleMembersDataPerAction: 'ScheduleMembersDataPerAction',
  SyncMembers: 'SyncMembers',
  scheduleTaskForEmptyAboutYouMembers: 'scheduleTaskForEmptyAboutYouMembers',
  convertHtmlToRichContent: 'convertHtmlToRichContent',
  CompileFiltersOptions: 'CompileFiltersOptions',
  scheduleTaskForExternalProfileImages: 'scheduleTaskForExternalProfileImages',
  convertExternalProfilesToWixImages: 'convertExternalProfilesToWixImages',
  updateSiteMapS3: 'updateSiteMapS3',
  scheduleEmailSync: 'scheduleEmailSync',
  syncMemberLoginEmails: 'syncMemberLoginEmails',
  scheduleContactFormEmailMigration: 'scheduleContactFormEmailMigration',
  migrateContactFormEmails: 'migrateContactFormEmails',
  scheduleMigrateExistingUrls: 'scheduleMigrateExistingUrls',
  migrateUrlsChunk: 'migrateUrlsChunk',
  scheduleGenerateMissingUrls: 'scheduleGenerateMissingUrls',
  generateUrlsChunk: 'generateUrlsChunk',
  scheduleCreateContactsFromMembers: 'scheduleCreateContactsFromMembers',
  createContactsFromMembers: 'createContactsFromMembers',
  scheduleFixPrimaryAddressForMembers: 'scheduleFixPrimaryAddressForMembers',
  fixPrimaryAddressChunk: 'fixPrimaryAddressChunk',
  scheduleFixUrlsWithSpaces: 'scheduleFixUrlsWithSpaces',
  fixUrlsWithSpacesChunk: 'fixUrlsWithSpacesChunk',
  scheduleDailyPullExecutionCheck: 'scheduleDailyPullExecutionCheck',
  dailyPullExecutionCheck: 'dailyPullExecutionCheck',
};

module.exports = {
  TASKS_NAMES,
};
